### ISSUE TITLE
//third_party/devtools-frontend/src/node_modules/fast-glob/out/ incorrectly missing from tarball

### ISSUE THREAD

**Issue by selfisekai** [chromium-linux-tarballs/chromium-tarballs#1]
I believe this is due to https://github.com/chromium-linux-tarballs/chromium-tarballs/blob/1b8df2dde019beb4a9c8f55247df13118a7c81b0/export_tarball.py#L73-L75

Causes rollup error in 132.0.6834.6:
```
ninja: job failed: python3 ../../third_party/node/node.py ../../third_party/devtools-frontend/src/node_modules/@rollup/wasm-node/dist/bin/rollup --silent --config ../../third_party/devtools-frontend/src/front_end/Images/rollup.config.mjs --input gen/third_party/devtools-frontend/src/front_end/Images/Images.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/Images/Images.js
Traceback (most recent call last):
  File "/home/lauren/aports/community/chromium/src/chromium-132.0.6834.6/out/bld/../../third_party/node/node.py", line 60, in <module>
    RunNode(sys.argv[1:])
  File "/home/lauren/aports/community/chromium/src/chromium-132.0.6834.6/out/bld/../../third_party/node/node.py", line 55, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '/home/lauren/aports/community/chromium/src/chromium-132.0.6834.6/out/bld/../../third_party/node/linux/node-linux-x64/bin/node ../../third_party/devtools-frontend/src/node_modules/@rollup/wasm-node/dist/bin/rollup --silent --config ../../third_party/devtools-frontend/src/front_end/Images/rollup.config.mjs --input gen/third_party/devtools-frontend/src/front_end/Images/Images.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/Images/Images.js' failed
[!] Error: Cannot find module '/home/lauren/aports/community/chromium/src/chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/out/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:445:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:716:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/lauren/aports/community/chromium/src/chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/@rollup/plugin-dynamic-import-vars/dist/cjs/index.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
ninja: subcommand failed
```

**Comment by Kangie** [comment]
Thanks. I hit this late last night, too. I'll regen the tarball and take a look.

This seems wrong - `export_tarball` is the same script used by Google's CI and `out/` indicates the transpiled output of node stuff. The current version upstream still strips `out`, too, which means if it's checked into the repo I'd expect failures there, too.

Since I did 132 first this week I'm pulling a new copy of the tag and I'll inspect the  tree and compare. Let you know what I come up with!

**Comment by Kangie** [comment]
Raised https://issues.chromium.org/issues/379140417 upstream.

**Comment by Kangie** [comment]
Hi @selfisekai

New tarball uploaded for 132.0.6834.6. It's still building on my end but looks good so far and does contain the appropriate `out` dir. Hopefully nothing else pops up!

```
tar tvf chromium-132.0.6834.6.tar.xz | grep -i fast-glob
drwxr-xr-x kangie/kangie         0 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/
-rw-r--r-- kangie/kangie      1079 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/LICENSE
-rw-r--r-- kangie/kangie     26161 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/README.md
drwxr-xr-x kangie/kangie         0 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/out/
-rw-r--r-- kangie/kangie      2176 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/out/index.d.ts
-rw-r--r-- kangie/kangie      4091 2024-11-15 16:20 chromium-132.0.6834.6/third_party/devtools-frontend/src/node_modules/fast-glob/out/index.js
```

**Comment by Kangie** [comment]
CDN updated, I've successfully built and pushed the Gentoo package. Closing for now; let me know if you're still having issues :)
